try {
} catch (Exception1 | Exception2 ex) {
}
